config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/urls.py
from django.shortcuts import render
from django.urls import path

from . import views

app_name = "portfolio"

urlpatterns = [
    path('index', views.index_view, name='index'),
    path('home', views.home_page_view, name='home'),
    path('blog', views.blog_page_view, name='blog'),
    path('novoAutor', views.novo_autor_view, name='novoAutor'),
    path('novoArtigo', views.novo_artigo_view, name='novoArtigo'),
    path('edita/<int:artigo_id>', views.edita_artigo_view, name='edita'),
    path('apaga/<int:artigo_id>', views.apaga_artigo_view, name='apaga'),
    path('novoComentario', views.novo_comentario_view, name='novoComentario'),
    path('comentarios<int:artigo_id>', views.comentarios_view, name='comentarios'),
    path('comentarios/<int:comentario_id>/like/', views.dar_like_comentario_view, name='dar_like_comentario'),
    path('playground.html', views.playground_view, name='playground'),
    path('login', views.login_view_autenticacao, name='login'),
    path('video', views.video_view, name='video'),
]

portfolio/models.py
from django.db import models


# Create your models here.


class Autor(models.Model):
    nome = models.CharField(max_length=250, null=False)
    apelido = models.CharField(max_length=250, null=False)
    email = models.CharField(null=False, max_length=100)
    verified = models.BooleanField(null=False)

    def __str__(self) -> str:
        return f'{self.nome} {self.apelido}'


class BlogOwner(models.Model):
    nome = models.CharField(max_length=100, null=False)
    repogit = models.CharField(max_length=1000, null=False)
    python = models.CharField(max_length=250, null=False)

    def __str__(self) -> str:
        return self.nome


class Blog(models.Model):
    nome = models.CharField(max_length=250, null=False)
    dono = models.OneToOneField(BlogOwner, on_delete=models.CASCADE, related_name="dono_blog")

    def __str__(self) -> str:
        return f'{self.nome}'


class Area(models.Model):
    nome = models.CharField(max_length=250, null=False)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="area_blog")

    def __str__(self) -> str:
        return self.nome


class Artigo(models.Model):
    titulo = models.CharField(max_length=250, null=False)
    conteudo = models.CharField(max_length=1000, null=False)
    imagem = models.ImageField(upload_to='images/', null=True, blank=True)
    link = models.CharField(max_length=250, null=False)
    area = models.ForeignKey(Area, on_delete=models.CASCADE, related_name="artigo_area")
    autor = models.ManyToManyField(Autor, related_name="artigo_autor")

    def __str__(self) -> str:
        return f'{self.titulo}: {self.conteudo}'


class Comentario(models.Model):
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE, related_name="comentario_autor")
    texto = models.CharField(max_length=1000, null=False)
    likes = models.IntegerField(default=0)
    artigo = models.ForeignKey(Artigo, on_delete=models.CASCADE, related_name="comentario_artigo")

    def __str__(self) -> str:
        return f'{self.autor}: {self.texto}: {self.likes}'


class Projeto(models.Model):
    titulo = models.CharField(max_length=250, null=False)
    descricao = models.CharField(max_length=250, null=False)
    imagem = models.ImageField(upload_to='images/', null=True, blank=True)
    cadeira = models.CharField(max_length=250, null=False)

    def __str__(self) -> str:
        return f'{self.titulo}: {self.descricao}: {self.cadeira}'

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class AutorForm(ModelForm):
    class Meta:
        model = Autor
        fields = '__all__'

        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'adicionar nome...'}),
            'apelido': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'adicionar apelido...'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'adicionar email...'}),
        }

        labels = {
            'nome': 'nome',
            'apelido': 'apelido',
            'email': 'email',
            'verified': 'verified',
        }


class ArtigoForm(ModelForm):
    class Meta:
        model = Artigo
        fields = '__all__'

        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'adicionar nome...'}),
            'conteudo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'adicionar apelido...'}),
            'link': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'adicionar link...'}),
        }

        labels = {
            'titulo': 'titulo',
            'conteudo': 'conteudo',
            'imagem': 'imagem',
            'link': 'link',
            'area': 'area',
            'autor': 'autor',
        }


class ComentarioForm(ModelForm):
    class Meta:
        model = Comentario
        fields = '__all__'

        widgets = {
            'texto': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'adicionar comentário...'}),
            'link': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'adicionar link...'}),
            'likes': forms.NumberInput(attrs={'disabled': 'True'}),
        }

        labels = {
            'autor': 'autor',
            'texto': 'texto',
            'likes': 'likes',
            'artigo': 'artigo',
        }

portfolio/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

from .forms import *
from .models import *


def home_page_view(request):
    return render(request, 'portfolio/home.html')


def index_view(request):
    context = {'projetos': Projeto.objects.all()}
    return render(request, 'portfolio/index.html', context)


def login_view_autenticacao(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request,
                            username=username,
                            password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('portfolio:blog'))

        else:
            return render(request, 'portfolio/login.html', {
                'message': "erro"
            })

    return render(request, 'portfolio/login.html')


def playground_view(request):
    return render(request, 'portfolio/playground.html')


def blog_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))

    context = {'artigos': Artigo.objects.all(),
               'autores': Autor.objects.all(),
               'comentarios': Comentario.objects.all()}

    return render(request, 'portfolio/blog.html', context)


def novo_autor_view(request):
    form = AutorForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('portfolio:blog')
    context = {'form': form}
    return render(request, 'portfolio/novoAutor.html', context)


def novo_artigo_view(request):
    form = ArtigoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('portfolio:blog')
    context = {'form': form}
    return render(request, 'portfolio/novoArtigo.html', context)


def novo_comentario_view(request):
    form = ComentarioForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('portfolio:blog')
    context = {'form': form}
    return render(request, 'portfolio/novoComentario.html', context)


def edita_artigo_view(request, artigo_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))

    artigo = get_object_or_404(Artigo, pk=artigo_id)

    if request.method == 'POST':
        form = ArtigoForm(request.POST, instance=artigo)
        if form.is_valid():
            form.save()
            return redirect('portfolio:blog')

    else:
        form = ArtigoForm(instance=artigo)

    context = {
        'artigo': Artigo,
        'artigo_id': artigo_id,
        'form': form,
    }

    return render(request, 'portfolio/edita.html', context)


def apaga_artigo_view(request, artigo_id):
    Artigo.objects.get(id=artigo_id).delete()
    return HttpResponseRedirect(reverse('portfolio:blog'))


def comentarios_view(request, artigo_id):
    artigo = Artigo.objects.get(pk=artigo_id)
    comentarios = Comentario.objects.filter(artigo=artigo)

    return render(request, 'portfolio/comentarios.html', {
        "artigos": artigo,
        "comentarios": comentarios
    })


def dar_like_comentario_view(request, comentario_id):
    comentario = get_object_or_404(Comentario, pk=comentario_id)
    comentario.likes += 1
    comentario.save()

    # redirecionar para a página de detalhes do artigo ou para onde você desejar
    return redirect('portfolio:comentarios', artigo_id=comentario.artigo.id)


def video_view(request):
    return render(request, 'portfolio/video.html')

portfolio/templates/portfolio/blog.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <div class="blog">
        <div class="autores">
            <h1>Autores</h1>
            <table id="autores">
            {% for autor in autores %}
                <tr>
                    <td>
                        {{ autor.nome }} {{ autor.apelido }}
                        {% empty %}
                        Não há Autores.
                    </td>
                </tr>
            {% endfor %}
            </table>
            <a href="{% url 'portfolio:novoAutor' %}" class="btn btn-success btn-block">Novo Autor</a>
        </div>

        <div class="artigos">
            <h1>Artigos</h1>
            {% for artigo in artigos %}
                <br><br>
                <table id="artigos">
                    <tr>
                        <th>Titulo</th>
                        <th>Conteúdo</th>
                        <th>Área</th>
                        <th>Editar</th>
                        <th>Ver Comentários</th>
                    </tr>
                    <tr>
                        <td>{{ artigo.titulo }}</td>
                        <td>{{ artigo.conteudo }}</td>
                        <td>{{ artigo.area }}</td>
                        <td><a href="{% url 'portfolio:edita' artigo.id %}" class="btn btn-warning">Editar</a></td>
                        <td><a href="{% url 'portfolio:comentarios' artigo.id %}" class="btn btn-success btn-block">Ver Comentários</a></td>
                    </tr>
                </table>
                <br><br><br><br><br>
            {% empty %}
                <li>Não há Artigos.</li>
            {% endfor %}
            <a href="{% url 'portfolio:novoComentario' %}" class="btn btn-warning" id="C">Novo Comentário</a>
            <a href="{% url 'portfolio:novoArtigo' %}" class="btn btn-success btn-block" id="A">Novo Artigo</a>
        </div>
    </div>
{% endblock main %}

portfolio/templates/portfolio/comentarios.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <div class="blog">
        <div class="comentarios">
            <div class="titleComentariosArtigo">
                <h1>Comentários do Artigo: {{ artigos.titulo }}</h1>
            </div>
            <br><br>
            <table id="comentarios">
                <tr>
                    <th>Autor:</th>
                    <th>Comentário:</th>
                    <th>Nr de Likes:</th>
                    <th>Botão de Like</th>
                </tr>
            {% for comentario in comentarios %}
                <tr>
                    <td>{{ comentario.autor }}</td>
                    <td>{{ comentario.texto }}</td>
                    <td>{{ comentario.likes }}</td>
                    <td>
                        <form action="{% url 'portfolio:dar_like_comentario' comentario.id %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <button type="submit" id="bttLikeComentario">Like</button>
                        </form>
                    </td>
                </tr>
                {% empty %}
                    <li>Não há comentários.</li>
            {% endfor %}
            </table>
        </div>
    </div>
{% endblock main %}

portfolio/templates/portfolio/edita.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <div class="blog">
        <div class="editarArtigo">
        <h3>Editar artigo</h3>
            <form action="{% url 'portfolio:edita' artigo_id %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}

                <a href="{% url 'portfolio:blog' %}" role="button">Cancelar</a>
                <input type="submit" value="Gravar" class="btn-gravaredit" >
                <a href="{% url 'portfolio:apaga' artigo_id %}" role="button" class="btn-apagaredit">Apagar</a>
            </form>
        </div>
    </div>
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Titulo</h3>
    <p>texto texto texto texto texto texto texto </p>

    {% load static %}
    <img src="{% static 'portfolio/images/phoca_thumb_l_image03_grd.png' %}">
{% endblock %}

portfolio/templates/portfolio/layout.html
<!-- base.html -->
<html lang="pt">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <link rel="stylesheet" href="{% static 'portfolio/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/style_pequeno.css' %}">
    <script src="{% static 'portfolio/js/scripts.js' %}" defer></script>
    <script src="{% static 'portfolio/js/scriptPlayground.js' %}"></script>
    <link rel="icon" type="image/x-icon" href="{% static 'portfolio/images/portfolio.ico' %}">
</head>
<body>
    <header class="header">
        <nav>
            <input id="responsive-menu" type="checkbox">
            <label for="responsive-menu" id="checkmenu">
                <span id="menu-icon"></span>
            </label>

            <button class="button-darkmode">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-moon-fill" viewBox="0 0 16 16">
                    <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
                </svg>
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="16" fill="currentColor" class="bi bi-brightness-high-fill" viewBox="-5 0 16 16">
                    <path d="M12 8a4 4 0 1 1-8 0 4 4 0 0 1 8 0zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
                </svg>
                <div class='ball'></div>
            </button>

            <span class="title">
                <span class="animate-charcter">B</span>runo <span class="animate-charcter2">M</span>iguel
            </span>

            <div id="myNav" class="overlay">
                <a href="javascript:void(0)" class="closebtn">&times;</a>
                    <div class="overlay-content">
                    <ul id="links">
                        <li><a href="{% url 'portfolio:index' %}" class="hover-underline">Inicio</a></li>
                        <li><a href="{% url 'portfolio:index' %}" class="hover-underline2" >Sobre mim</a></li>
                        <li><a href="{% url 'portfolio:index' %}" class="hover-underline3" >Projetos</a></li>
                        <li><a href="{% url 'portfolio:index' %}" class="hover-underline4" >Contacto</a></li>
                        <li><a href="{% url 'portfolio:playground' %}" class="hover-underline">PlayGround</a></li>
                        <li><a href="{% url 'portfolio:blog' %}"  class="hover-underline">Blog</a></li>
                        <li><a href="{% url 'portfolio:video' %}"  class="hover-underline">Video</a></li>
                    </ul>
                    <ul id="social-media">
                        <li>
                            <a href="https://github.com/brunomiguel22106424">
                                <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-github" viewBox="-5 -5 25 25">
                                    <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
                                </svg>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.linkedin.com/in/bruno-miguel-985771233/">
                                <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-linkedin" viewBox="-5 -5 25 25">
                                    <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"></path>
                            </svg>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        {% block firstcontent %}
        {% endblock firstcontent %}
    </div>
    <div>
        {% block secondcontent %}
        {% endblock secondcontent %}
    </div>
	<div>
        {% block main %}
        {% endblock main %}
    </div>
	<div>
        {% block projetos %}
        {% endblock projetos %}
    </div>
    <div>
        {% block skills %}
        {% endblock skills %}
    </div>
    <div>
        {% block terceiracontent %}
        {% endblock terceiracontent %}
    </div>
    <div>
        {% block calculadora %}
        {% endblock calculadora %}
    </div>
    <div>
        {% block playgroundpt2 %}
        {% endblock playgroundpt2 %}
    </div>
    <div>
        {% block login %}
        {% endblock login %}
    </div>
    <div>
        {% block video %}
        {% endblock video %}
    </div>
    <div class="footer">
        <div class="footer1 info1">
            <h1>Portfolio</h1>
            <div id="linha"></div>
            <div class="acessos">
                <div class="acesso1" id="hover-underline"><a href="{% url 'portfolio:index' %} ">Inicio</a></div>
                <span class="barra-separacao">|</span>

                <div class="acesso1" id="hover-underline"><a href="{% url 'portfolio:index' %}">Sobre mim</a></div>
                <span class="barra-separacao">|</span>

                <div class="acesso1" id="hover-underline"><a href="{% url 'portfolio:index' %}">Projetos</a></div>
                <span class="barra-separacao">|</span>

                <div class="acesso1" id="hover-underline"><a href="{% url 'portfolio:index' %}">Contacto</a></div>
                <span class="barra-separacao">|</span>

                <div class="acesso1" id="hover-underline"><a href="{% url 'portfolio:blog' %}">Blog</a></div>
            </div>
            <div class="footer-socialmedia">
                <a href="https://github.com/brunomiguel22106424">
                    <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-github" viewBox="-5 -5 25 25">
                        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
                    </svg>
                </a>
                <a href="https://www.linkedin.com/in/bruno-miguel-985771233/">
                    <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-linkedin" viewBox="-5 -5 25 25">
                        <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"></path>
                </svg>
                </a>
            </div>
            <div class="copyright">
                <p>Bruno Miguel Soares - Copyright © 2023</p>
            </div>
        </div>
        <div class="footer2">
            <div id="localidade">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                    <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"></path>
                </svg>
                <h2>Localização</h2>
                <p>Campo Grande 376, 1749-024 Lisboa</p>
            </div>
            <div id="telemovel">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"></path>
                </svg>
                <h2>Telemóvel</h2>
                <p>+351 999 999 999</p>
            </div>
            <div id="email">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-open" viewBox="0 0 16 16">
                    <path d="M8.47 1.318a1 1 0 0 0-.94 0l-6 3.2A1 1 0 0 0 1 5.4v.817l5.75 3.45L8 8.917l1.25.75L15 6.217V5.4a1 1 0 0 0-.53-.882l-6-3.2ZM15 7.383l-4.778 2.867L15 13.117V7.383Zm-.035 6.88L8 10.082l-6.965 4.18A1 1 0 0 0 2 15h12a1 1 0 0 0 .965-.738ZM1 13.116l4.778-2.867L1 7.383v5.734ZM7.059.435a2 2 0 0 1 1.882 0l6 3.2A2 2 0 0 1 16 5.4V14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V5.4a2 2 0 0 1 1.059-1.765l6-3.2Z"></path>
                </svg>
                <h2>Email</h2>
                <p>brunomiguel.bcs@gmail.com</p>
            </div>
            <div id="linhafooter2"></div>
        </div>
        <div class="footer3">
            <p>Universidade Lusófona - Centro Universitário Lisboa</p>
            <img src="{% static 'portfolio/images/lusofonalogo.png' %}" alt="Logotipo da Lusófona">
        </div>
    </div>
</body>
</html>

portfolio/templates/portfolio/login.html
{% extends 'portfolio/layout.html' %}

{% block login %}
    <div class="login_content">
        <form class="form-login" method="post" action="{% url 'portfolio:login' %}">
            {% csrf_token %}
            <label for="username">User</label>
            <input type="text" id="username" name="username">
            <label for="password">Password</label>
            <input type="password" id="password" name="password">
            <button type="submit" class="btn-gravar">Submit</button>
        </form>
    </div>
{% endblock login %}

portfolio/templates/portfolio/novoArtigo.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <div class="blog">
        <div class="novoArtigo">
        <h3>Novo Artigo</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}

                <a href="{% url 'portfolio:blog' %}" class="btn btn-warning">Cancelar</a>
                <input type="submit" value="Gravar" class="btn-gravar" >
            </form>
        </div>
    </div>
{% endblock %}

portfolio/templates/portfolio/novoAutor.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <div class="blog">
        <div class="novoAutor">
            <h3>Novo Autor</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}

                <a href="{% url 'portfolio:blog' %}" class="btn btn-warning">Cancelar</a>
                <input type="submit" value="Gravar" class="btn-gravar" >
            </form>
        </div>
    </div>
{% endblock %}